### ISSUE TITLE
probleme node module

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#1]
Hi when i create a new project with this command 

npx rn-nano init MyFirstNanoProject

 I have this issue :

 BUNDLE  ./index.js

error: SyntaxError: C:\Users\Mega-PC\Desktop\nano\MyFirst\App\index.js: Unexpected token, expected "," (7:4)

   5 | const  countText = {
   6 |     name:"text"
>  7 |     component:  NANO.TEXT,
     |     ^
   8 |     value:  1,
   9 |     props: {
  10 |     style: {

 this is my App/index.js
 
 import { NANO } from  'react-native-nano';

// creating a text component to display numbers starting from 1.
const  countText = {
    name:"text"
    component:  NANO.TEXT,
    value:  1,
    props: {
    style: {
        fontSize:  50,
        alignSelf:  'center',
        justifyContent:  'center',
    }
    }
};

// creating a button component to click and increase number.
const  increaseCountButton = {
    component:  NANO.BUTTON,
    value:  'CLICK ME TO INCREASE',
    onPress: ({setUi, getUi}) => {

            // increase count by 1
            const textObj = getUi("text")
            textObj.value = textObj.value + 1
            setUi("text", textObj)
            
    }
};

// Finally adding both components to screen with v1(vertical) tag.
const screen = {
    name: 'WelcomeScreen',
    screen: {
    v1: [countText, increaseCountButton],
    },
    style: { flex: 1, justifyContent: 'center' },
};

const  App = () => {
    return <NANO screens={[screen]} />;
};
export  default  App;

**Comment by sandeshnaroju** [comment]
Thanks for trying the framework, once you have created project using this command below,
```
npx rn-nano init MyFirstNanoProject
```
You can directly run the app `npm run android` this will load a simple hello world app. 

You can also replace with the below code into your `App.js` file for loading a simple counter app.

``` javascript
import {RNNano, NANO} from  'react-native-nano';
	
// creating a text component to display numbers starting from 1.
const  countText = {
    component:  NANO.TEXT,
    name:'text',
    value:  1,
    props: {
	style: {
	    fontSize:  50,
	    alignSelf:  'center',
	    justifyContent:  'center',
	}
    }
};

// creating a button component to click and increase numbers.
const  increaseCountButton = {
    component:  NANO.BUTTON,
    value:  'CLICK ME TO INCREASE',
    onPress: ({setUi, getUi}) => {

            // increase count by 1
            const textObj = getUi("text")
            textObj.value = textObj.value + 1
            setUi("text", textObj)

    }
};

// Finally adding both components to screen with v1(vertical) tag.
const screen = {
    name: 'CountScreen',
    screen: {
	v1: [countText, increaseCountButton],
    },
    style: { flex: 1, justifyContent: 'center' },
};


const  App = () => {
    return <RNNano screens={[screen]} />;
};
export  default  App;
```
Let me know if you are able to do it.

**Comment by beyons** [comment]
the problem is that the react-native-nano module I cannot find it in the generate folder

**Comment by sandeshnaroju** [comment]
Ok. Understood, kindly downgrade the version and you can run `npm install react-native-nano@1.0.90` to use previous version while fix the problem.

**Comment by beyons** [comment]
Ok i will test this verssion 1.0.90
Thank you

really congratulations for the work done

**Comment by beyons** [comment]
when i create a new project i have this error

![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/8472b848-81e1-434a-9f04-27e43899afaa)

**Comment by beyons** [comment]
When i install all the dependency and i created manually the file nano.config  


export const RELOAD_TIME = '500';
export const THEMES = null;

const newTable = {
  name: 'user',
  properties: {
    key: 'string',
    value: 'string', 
  },
  primaryKey: 'key',
};

export const DataBaseConfig = {
   schema: [newTable],
   schemaVersion: 3,
};
export const CLIENT_ID = '123123';
export const CLIENT_SECRET = '321321';
export const APP_URL = 'com.nano.naotest';

i have this error


![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/e6aafe1e-0ae9-4e28-8882-797a4529eee5)

**Comment by beyons** [comment]
windows 10

**Comment by beyons** [comment]
i would test only android

**Comment by sandarshnaroju** [comment]
`npx rn-nano init myfirstapp` installs react native and `react-native-nano` and downloads other required files from a starter template via `curl`, 
`curl` command didn't work so, make sure u can run `curl` in your system . 

`npx rn-nano init myfirstapp` also installs 'realm' for database via `npm install realm` command.  have you run any other RN apps with realm in windows? 

Can you run `npm install realm` in your root and try again . 

Also reset cache via `npm run start --reset-cache`.

**Comment by beyons** [comment]
and for the nano.config file ?

**Comment by beyons** [comment]
![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/d35e7569-119a-4e86-ae9e-27ff1ebf6df2)

**Comment by sandarshnaroju** [comment]
> and for the nano.config file ?

`npx rn-nano init myfirstapp` command itself downloads all required files. 
But in your case ,it encountered an error with `curl` , so it didn't download other files such as `nano.config.js`.

**Comment by beyons** [comment]
its impossible to download nano.config.js manually

**Comment by beyons** [comment]
the same problem with 5 PC

**Comment by sandarshnaroju** [comment]
> its impossible to download nano.config.js manually

`nano.config.js` file should be in root of the project directory with the below content

```
export const CLIENT_ID = "id"; 
export const CLIENT_SECRET = "secret"; 
export const RELOAD_TIME = 10000; 
 const lightTheme = {
  name: "light",
  isDark: false,
  colors: {
    primary: "blue",
    secondary: "#800460",
    background: "#e0f4f4",
  },
};
const darkTheme = {
  name: "dark",
  isDark: true,
  colors: {
    primary: "black",
    secondary: "yellow",
    background: "gray",
  },
};

export const THEMES = [lightTheme, darkTheme];
  
export const DataBaseConfig = { 
 // schema:"your schema object" , 
 // schemaVersion: "", 
} ;   
```

**Comment by beyons** [comment]
![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/ee07f3a7-8c66-40fb-8279-c953630ab518)

**Comment by sandarshnaroju** [comment]
> ![image](https://user-images.githubusercontent.com/69459996/272224570-ee07f3a7-8c66-40fb-8279-c953630ab518.png)

Are you running the `npx rn-nano init myapp` command normally or in Administrative privileges ?? 

If running normally, try running it with Administrative privileges

**Comment by beyons** [comment]
![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/9ec0bcf2-43c0-4eb9-9dc2-725c0cd8fa47)

**Comment by sandarshnaroju** [comment]
I want you to confirm a couple of things

a) Is `curl` running in your system??
b) Have you succesfully setup a RN project before in your system??

After that, Just for testing try to clone this repo https://github.com/sandarshnaroju/nano-starter-template and run it.
This is where `npx rn-nano init myfirstapp` downloads required files while setting up project. This is an outdated `rn-nano` repo. But for testing this will do.

If you are able to run it then, I will update it to latest version.

**Comment by beyons** [comment]
Curl work fine in my PC
Yes i have configurated a RN project in my PC (expo project)
with this repo that's work fine i showed a welcome header

**Comment by sandarshnaroju** [comment]
> Curl work fine in my PC Yes i have configurated a RN project in my PC (expo project) with this repo that's work fine i showed a welcome header

That means, `npx rn-nano init` code has some bug and doesn't work in Windows. Will fix it for windows and let you know. 

meanwhile you can use https://sandarshnaroju.github.io/ to see how Nano works.

**Comment by sandeshnaroju** [comment]
We are still working to get ready for windows also with proper documentation. `Alert` is not included in the framework yet.  It will be added in the next update. I will update soon.

**Comment by beyons** [comment]
I was able to get alert from react native to work

**Comment by sandeshnaroju** [comment]
You can see how to use alert and remaining modules here https://docs.nanoapp.dev/docs/modules/all after updating to latest react-native-nano version using below command.

``` bash
npm install react-native-nano@1.0.108

```

For now I am closing this issue. Feel free to open new issue in case if you have any questions.

**Comment by sandeshnaroju** [comment]
We have added support for windows installation,  you can use the same commands to install like below.

``` bash

 // below will create with nano and react-native latest version
npx rn-nano init MyAwesomeProject 

// below will create nano and react-native project with specific versions. 
npx rn-nano init MyAwesomeProject  --nano-version 1.0.112  --rect-native-version 0.72.6  


```
