### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#13]
Hello, i have update react-native nano to the last version and add react-native reanimated  but i have this error now

![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/f03fa0d1-9104-40eb-af03-2c4e69209f2e)

**Comment by sandarshnaroju** [comment]
Hey , We need more info to help you. 
1) Which version of `react-native-nano` are you using??
2) It looks like you are trying to update `react-native-nano`, can you tell us more info about from which version you updated it to the latest one. 
For installing and using `react-native-reanimated` separately,  you have to add `react-native-reanimated/plugin` in the `babel.config.js`. check if you have done that. More details can be found [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#step-2-add-reanimateds-babel-plugin).

Easiest way forward for you is using `npx rn-nano init MyAwesomeApp` and replacing the JSON code in the new app. Here you don't have to install `react-native-reanimated` separately. It is installed and setup automatically. 

To use Animations with `react-native-nano`, checkout our updated docs at [docs.nanoapp.dev](https://docs.nanoapp.dev/docs/animation/quick-start) .

**Comment by beyons** [comment]
Hi when i added the last version of react native nano and added reanimated my previous version  [1.0.157] when i update react native nano to the last version and add reacnimated i have this error ,

this error is from reanimated library because without this library i can build the apk  but with this library i cannot

**Comment by beyons** [comment]
strange when i used this command i have this error now 

`
√ Downloading template
√ Copying template
√ Processing template
√ Installing dependencies
error EBUSY: resource busy or locked, unlink 'C:\Users\Mega-PC\AppData\Local\Temp\rncli-init-template-BLYrTo\node_modules\type-fest\source\merge-exclusive.d.ts'.
Error: EBUSY: resource busy or locked, unlink 'C:\Users\Mega-PC\AppData\Local\Temp\rncli-init-template-BLYrTo\node_modules\type-fest\source\merge-exclusive.d.ts'
    at Object.unlinkSync (node:fs:1860:3)
    at rimrafSync (C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:254:15)
    at C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:281:7)
    at rimrafSync (C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:252:7)
    at C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Mega-PC\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
info Run CLI with --verbose flag for more details.
Failed to execute npx react-native init MyAwesomeApp --version 0.71.3 Error: Command failed: npx react-native init MyAwesomeApp --version 0.71.3
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runCommand (C:\Users\Mega-PC\AppData\Roaming\npm\node_modules\rn-nano\bin.js:29:5)
    at initialiseReactNativeProjectAndDeleteApptsxFile (C:\Users\Mega-PC\AppData\Roaming\npm\node_modules\rn-nano\bin.js:159:22)
    at setUpANewMinimalProject (C:\Users\Mega-PC\AppData\Roaming\npm\node_modules\rn-nano\bin.js:211:3)
    at C:\Users\Mega-PC\AppData\Roaming\npm\node_modules\rn-nano\bin.js:298:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12316,
  stdout: null,
  stderr: null
}
`
and in my node module i dont have all  dependencies 

![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/e4717922-a4c0-4e70-aa27-106532b90cc7)

**Comment by beyons** [comment]
and this is package.json

![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/246b366f-0346-4ca0-8bb3-641d9cd29696)

**Comment by sandarshnaroju** [comment]
Based on the error, it looks like `npm` wants to access a file , but that file is being used by another program.

As per a similar issue [here](https://github.com/npm/npm/issues/13461)
You can try `npm cache clean` and rerunning the command `npx rn-nano init Myawesomeapp`.

If that doesnt work, try to rerun the command after turning off your antivirus  and also closing vscode or any other file editors.

**Comment by beyons** [comment]
a new error now 
![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/15d73361-329d-4709-b77c-c2919f8a4c76)

 actually i downgraded my apps to 1.0.157 and my apps work but when i update react native nano i have problem with react native reanimated

**Comment by sandarshnaroju** [comment]
Did you try above three solutions??

**Comment by beyons** [comment]
Yes all three didn't work for me and i cannot create a new app because i have this error in all the pc

**Comment by sandarshnaroju** [comment]
I am working on it. will get back to you as early as possible.

**Comment by sandarshnaroju** [comment]
Ok, The problem seems to be from compatibility issues between different versions of `react-native` and `react-native-reanimated`. You have two options now. 

If you are ok with using little older React-Native version(0.71.4) you can directly use `npx rn-nano init awesomeproject --react-native-version 0.71.4`. Generated project will  have react-native-reanimated (3.6.2) installed. Everything works as expected.

If you want to use the latest React native version(0.74.0) , first do `npx rn-nano init awesomeproject` and then update react-native-reanimated via `npm install react-native-reanimated@3.9.0`. Finally go to `presets` in `babel.config.js` and replace  `module:metro-react-native-babel-preset` with `@react-native/babel-preset`. Run the app and everything should work as expected.

I will update the `rn-nano` cli-tool code so that these compatibility issues wont happen in the future. but that will take some time. Till then you can follow the above methods. Let me know how it went.

**Comment by beyons** [comment]
hi when i creant with npx rn nano init
i have this error

![image](https://github.com/sandarshnaroju/react-native-nano/assets/69459996/67898196-6619-4632-8de7-2a68e49f3368)
on windows i dont have all moduls like react native nano and reanimated in node module but in chrome os i have all moduls

**Comment by sandarshnaroju** [comment]
What command did u run?

**Comment by sandarshnaroju** [comment]
Try it now, should work

**Comment by beyons** [comment]
HI it work form me i can create project with npx rn-nano init awesomeproject --react-native-version 0.71.4 on windows and on chrome os  in all my pc

**Comment by sandarshnaroju** [comment]
Thanks for replying. 
I am closing this issue now. Feel free to open new issues if you encounter any other problem.
