### ISSUE TITLE
A problem with building new application 

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#15]
hi i have created a new project  but when i build a project i havec a problem with notifee 
with blank project i have a problem with notifee
this error : 

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve app.notifee:core:+.
     Required by:
         project :app > project :notifee_react-native
      > Failed to list versions for app.notifee:core.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/app/notifee/core/maven-metadata.xml.
            > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/app/notifee/core/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by beyons** [comment]
i have created new blank project ( only with  npx use-nano init MyFirstNanoProject  ) same error


BUILD FAILED in 2m 24s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:processDebugResources'. > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'. > Could not resolve app.notifee:core:+. Required by: project :app > project :notifee_react-native > Failed to list versions for app.notifee:core. > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/app/notifee/core/maven-metadata.xml. > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/app/notifee/core/maven-metadata.xml'. Received status code 504 from server: Gateway Time-out * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 2m 24s.
info Run CLI with --verbose flag for more details.

**Comment by beyons** [comment]
it's good the problem is with my notifee version

**Comment by beyons** [comment]
{
  "name": "MyFirstNanoProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@maplibre/maplibre-react-native": "^10.0.0-alpha.28",
    "@notifee/react-native": "^9.1.3",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-native-community/netinfo": "^11.4.1",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-device-info": "^10.13.2",
    "react-native-get-location": "^5.0.0",
    "react-native-image-crop-picker": "^0.41.1",
    "react-native-nano": "^1.0.163",
    "react-native-pager-view": "^6.3.1",
    "react-native-permissions": "^3.6.1",
    "react-native-reanimated": "^3.9.0",
    "react-native-rsa-native": "^2.0.5",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-storage": "^1.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^13.12.5",
    "realm": "^11.10.2",
    "rn-nano-sync": "^1.0.7"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.83",
    "@react-native/eslint-config": "0.74.83",
    "@react-native/metro-config": "0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

**Comment by beyons** [comment]
sorry i have another problem i cannot show my custom component  this is my code

customWebView.js

import React, {useEffect} from 'react';
import { WebView } from 'react-native-webview';

const MyWebComponent = ({ elementProps, getViewItems, onElementLoaded }) => {
  useEffect(() => {
    onElementLoaded(elementProps);
  }, []);

  return (
    <WebView
      {...elementProps['props']}
      {...elementProps}
    />
  );
}

export default MyWebComponent;

customPackagewebView.js


import MyWebComponent from './customWebView'

const customWebViewComponents = [
    {
      "name" :  "custom-wev-view",
      components:[
        {
          name:'custom_view_web_component', // name to use the component
          component:MyWebComponent, // our actual customComponent
        }
    ]  
    }
  ]
export default customWebViewComponents;


my apps.js


/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import {NanoApp} from 'react-native-nano';
/*** COMPONENTS ***/
import SplashScreen from './App/SplashScreen';
import LoginScreen from './App/LoginScreen';
import RegisterScreen from './App/RegisterScreen';

import customPackage from './App/customPackageWebView';

/*** ENTRY POINT ***/
const  App = () => {
    return <NanoApp packages={[customPackage]} screens={[
        SplashScreen,
        LoginScreen,
        RegisterScreen
    ]} />;
};

export default App;




but i show nothin i show no such components

**Comment by sandarshnaroju** [comment]
You correctly defined a custom package, but are not using it. To render your `custom_view_web_component` in a screen. You can do as below 

```

const  customView = {
  package:'custom-web-view', // your custom package name as defined in the file  customPackagewebView.js
  name:"my_custom_view",
  component:  'custom_view_web_component', // you custom component name as defined in the file  customPackagewebView.js
  
  props: {
// props for your custom_view_web_component goes here
      style: {
          alignSelf:  'center',
          justifyContent:  'center'
          backgroundColor:'blue',
// style custom_view_web_component as required here
      }
  }
};


const screen = {
    name: 'HomeScreen',
    screen: {
      v1: [customView], // rendering your custom_view_web_component 
    },
    props: {
      style: { flex: 1, justifyContent: 'center' }
    }
};
```

**Comment by beyons** [comment]
hello any soolution about this problem ? how can i use custom package i have testes in more new application but not work for me

**Comment by sandarshnaroju** [comment]
Sorry for the delay, there is a mistake in docs regarding implementation of custom components. The array of custom components in a custom package must be given to key named `package`. Will be fixed.


So in your case, your code needs following changes in customPackagewebView.js 


customPackagewebView.js


```
import MyWebComponent from './customWebView'

const customWebViewComponents = {
      "name" :  "custom-wev-view",
       package:{            // This was the mistake 

              components:[
                {
                  name:'custom_view_web_component', // name to use the component
                  component:MyWebComponent, // our actual customComponent
                },
            ]  ,
       },
    }
export default customWebViewComponents;



```

**Comment by sandarshnaroju** [comment]
If you are on Whatsapp, you can join our [Whatsapp group](https://chat.whatsapp.com/LsjmJatjNChFVFHPyFieaf) for instant help. 
Have a great day.

**Comment by beyons** [comment]
ok thank you :))) i will join

**Comment by sandarshnaroju** [comment]
Did u try my code?? Did it work?

**Comment by beyons** [comment]
thank you a lot i try your code that work fine now i can use all my custom widgets

**Comment by sandarshnaroju** [comment]
In react-native-nano version 1.0.174, `package` key while defining custom packages is removed. 

So now defining a custom package named "custom-package" with component "custom_list_view" will be like

```javascript
<NanoApp
       packages={[
        {
          name: 'custom-package',

          components: [
            {
              name: 'custom_list_view', // name to use the component
              component: DemoRecyclerList, // our actual customComponent
            },
          ],
 
          appStart: ({moduleParams}) => {
        
          },

        },
      ]}
  .....
     
    />

```
