### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#2]
hello, I was able to create a project with the latest version of react and nano and it works very well I had to import all the dependencies manually but I cannot use navigation

this is my index ( ERROR  ReferenceError: Can't find variable: navigation )

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */
import React from 'react';
import { NANO } from  'react-native-nano';
import {RNNano} from  'react-native-nano';
import { Alert } from 'react-native';  
import NetInfo from "@react-native-community/netinfo";

/**
 * 
 * Component Definition
 *
 */
const avatar_image = {
  component: NANO.AVATAR_IMAGE,
  value:
    'https://miro.medium.com/v2/resize:fit:1024/1*QY5S4senfFh-mIViSi5A_Q.png',
  props: {
    size: 250,
    color: 'red',
    style: {backgroundColor: 'blue',alignSelf:  'center', justifyContent:  'center'}
  }
};

const  countText = {
  component:  "text",
  name:'text',
  value:  "Welcome",
  props: {
  style: {
      color: "white",
      fontSize:  30,
      alignSelf:  'center',
      justifyContent:  'center',
  }
  }
};

const headerText = {
    component: "text",
    value: 'Todo App',
    props: {
        style: { fontSize: 16, fontWeight: "bold", textAlign: "center", color: "white", paddingVertical: 12, backgroundColor: "#6559cc", position: "absolute", top: 0, left: 0, right: 0, zIndex: 3 }
    }
};

const loginInput = {
    component: "text_input",
    name: "text_input1",
    props: {
      style: {  marginTop: 70, width:220, alignSelf:  'center', justifyContent:  'center' },
      color: 'blue',
      mode: "outlined",
      label: "Login",
      placeholder: "Add our login ...",
    }
};

const passwordInput = {
    component: "text_input",
    name: "text_input",
    props: {
      style: { width:220, alignSelf:  'center', justifyContent:  'center', marginTop: 5 },
      mode: "outlined",
      label: "Pwd",
      placeholder: "Add our password ...",
    }
    
};

const  countText1 = {
  component:  "text",
  name:'text',
  value:  "Welcome to \nReact Native Apps",
  props: {
  style: {
      fontSize:  30,
      alignSelf:  'center',
      justifyContent:  'center',
  }
  }
};

const connexion = {
  component: NANO.BUTTON,
  canChangeEffect: true,
  value: 'Connection',
  props: {
      style: { marginTop: 20, width:220, alignSelf:  'center', justifyContent:  'center', elevation: 5, backgroundColor: '#6559cc' },
      color: "white",
      mode: "outlined",
      borderRadius: 10,
  },
  hide: false,
  onPress: ({setUi, getUi}) => {

      // increase count by 1
      const textObj = getUi("text")
      textObj.value = textObj.value + 1
      setUi("text", textObj)

  }
};

const fab = {
  component: NANO.BUTTON,
  canChangeEffect: true,
  value: '+',
  props: {
      style: { position: 'absolute', margin: 16, right: 0, bottom: 0, marginTop: 20, width: 64, height: 64, alignSelf:  'center', justifyContent:  'center', elevation: 5, backgroundColor: '#e74c3c',borderTopLeftRadius: 50,borderTopRightRadius: 50, borderBottomLeftRadius: 50, borderBottomRightRadius: 50,textSize: 45 },
      color: "white",
      mode: "outlined",
      borderRadius: 10,
  },
  hide: false,
  onPress: ({setUi, getUi}) => {
      
  }
};

/**
 * 
 * Screen definition
 *
 */

const splashScreen = {
  name: 'SplashScreen',
  screen: {
    v1: [avatar_image, countText],
  },
  onStart:({ route, setUi, getUi })=>{
        NetInfo.fetch().then(state => {
            if( state.isConnected == true ){
                setTimeout((e)=>{
                    navigation.push("loginScreen")    
                },1000)
            }
            else{
                Alert.alert("Error:: network connection failed, Check your connection.");
            }
        });
  },
  onEnd:({ route, setUi, getUi })=>{
  
  },
  screenProps: {
      options: {
          "headerShown": false
      }
  },
  style: { flex: 1, justifyContent: 'center', backgroundColor: "#222222" },
};

const loginScreen = {
  name: 'loginScreen',
  screen: {
    v1: [countText1, loginInput, passwordInput, connexion, fab],
  },
  onStart:({ route, setUi, getUi })=>{
        NetInfo.fetch().then(state => {
            if( state.isConnected == true ){}
            else{
                Alert.alert("Error:: network connection failed, Check your connection.");
            }
          
        });
  },
  onEnd:({ route, setUi, getUi })=>{
  
  },
  screenProps: {
      options: {
          "headerShown": false
      }
  },
  style: { flex: 1, justifyContent: 'center' },
};

/**
 * 
 * App generation
 *
 */

const  App = () => {
    return <RNNano screens={[
                              splashScreen,
                              loginScreen
                           ]} />;
};
export  default  App;

**Comment by sandeshnaroju** [comment]
Unfortunately, we have not completed the documentation part of using nano framework completely, But I will try to explain in short how you can use nano framework, the latest version of nano has lot of changes those were not included in documentation here https://docs.nanoapp.dev/docs/intro. To use any module like navigation, you don't have to import, those are already available readily in all the methods, for example to open a new screen you can use navigation from moduleParams in a onPress

```
const button = {
    component: NANO.BUTTON,
    value:"CLICK ME"
    props: {
        style: {
        },
    },
    onPress: ({ moduleParams }) => {
        moduleParams["navigation"].navigate("SearchScreen") 
    }
}
```

You can simply print moduleParams in console.log(moduleParams) and check all the available moduleParams.

**Comment by beyons** [comment]
oh thank you thats work for me :))) thnaks you so much 

I'm going to use the framework for a relatively small client project, I hope I won't bother you if I have any other questions

**Comment by sandeshnaroju** [comment]
You can pass the data like below with navigation itself from ScreenA.

``` javascript
const buttonPress = {
  component: NANO.BUTTON,
  value: 'CLICK ME TO MOVE TO SCREEN B',
  onPress: ({ moduleParams }) => {
        moduleParams["navigation"].navigate("ScreenB", { "name": "value" }) 
    }
};

const screen = {
  name: 'ScreenA',
  screen: {
    h1: [buttonPress],
  }
};
```

And you can read data from ScreenB like from any method, usually you can read data from `onStart` method of screen like below

``` javascript
const text2 = {
  component: NANO.TEXT,
  value: "I AM IN SCREEN B",
};

const screen = {
  name: 'ScreenB',
  screen: {
    h1: [text],
  },
  onStart: ({moduleParams}) => {
      console.log( moduleParams["route"].params["name"])
  }
};

```

**Comment by Komarams** [comment]
> oh thank you thats work for me :))) thnaks you so much
> 
> I'm going to use the framework for a relatively small client project, I hope I won't bother you if I have any other questions
> 
> and how to pass and retrieve data between screen??

No problem at all, feel free to ask questions

**Comment by sandarshnaroju** [comment]
> oh thank you thats work for me :))) thnaks you so much
> 
> I'm going to use the framework for a relatively small client project, I hope I won't bother you if I have any other questions
> 
> and how to pass and retrieve data between screen??

> oh thank you thats work for me :))) thnaks you so much
> 
> I'm going to use the framework for a relatively small client project, I hope I won't bother you if I have any other questions
> 
> and how to pass and retrieve data between screen??

No problem at all, feel free to ask questions. 

All functional props a component can have like (`onPress` , `onLongPress` etc for `button`), will have parameters in their callback for you to use. 

```
 onPress: ({ moduleParams, getUi, setUi, methodValues, componentParams }) => {
        moduleParams["navigation"].navigate("ScreenB", { "name": "value" }) 
    }
```
`moduleParams` contains functions and values related to `navigation` , `themes` , `db` , `ImagePicker` , `Permissions` , `deviceDimensions` , `DeviceInfo` etc. This might change as we update the project .

`getUi` is to get the component Object via its `name` . 
`setUi` is to let Nano know when to change the component and rerender.
`methodValues` is useful to access parameters returned by element itself . For example, in a textInput, you can access what user typed from `methodValues` in the `onChangeText` method.

**Comment by beyons** [comment]
they have a DB module ? How can i use it ?
Also how can i use deviceInfo and Notification?

Thank you for all :)

**Comment by beyons** [comment]
great thank you

**Comment by sandeshnaroju** [comment]
Thanks for waiting, we have updated the documentation here https://docs.nanoapp.dev/ . 

Kindly update the react-native-nano version to latest and check documentation. 
``` bash
   npm install react-native-nano@1.0.108

```

You can see all the available modules here https://docs.nanoapp.dev/docs/modules/all and their usage. 

Database: https://docs.nanoapp.dev/docs/modules/database


Feel free to ask more questions if you have any. 

Thanks
