### ISSUE TITLE
Question about load ui from server

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#3]
Hi i have a question about this things

Ability to load UI (JSON) from your own server
how can i made this ability

**Comment by sandeshnaroju** [comment]
Hey thanks again for your interest, loading ui from server is something we have completed internally and but not added completely to the framework, we are working to make it available in the next 7 days. It will be an extension version of https://sandarshnaroju.github.io/  where you can code from browser and see results in your physical device app or in browser simulator.  And also you can download code. Kindly be patient.  Please check our updated documentation here at docs.nanoapp.dev for detailed documentation.

**Comment by sandeshnaroju** [comment]
Hey thanks for waiting, we have launched a beta version of creating app in browser and loading ui to locally running npm project. Kindly visit https://sandarshnaroju.github.io/ and start creating your first app. Please let me the know how you feel. Thanks.

**Comment by beyons** [comment]
Hi o great, how it work ?
