### ISSUE TITLE
Informations about this framework

### ISSUE THREAD

**Issue by beyons** [sandarshnaroju/react-native-nano#6]
Hi i have a question this framework is a static framework or a dynamic framework i mean  can i use the animation in every view or not yet implemented ?
thank you a lot

**Comment by sandeshnaroju** [comment]
Hey, thanks for using this framework. Yes, we support animations from [react-native-animatable](https://github.com/oblador/react-native-animatable) package, here is how you can use animation for a component.

```js
const  countText = {
  component:  NANO.TEXT,
  name:'text',
  value:  1,
  props: {
    style: {
        fontSize:  50,
        alignSelf:  'center',
        justifyContent:  'center',
    }
  },
  animation:{ 
    animation:"rotate", 
    delay:1000,
    iterationCount: "infinite" 
  }
};
```
An you can add the above text component in your screen.
